foodle/foodle/urls.py
from django.contrib import admin
from django.urls import path
from ingredients import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path(
        'ingredients/', 
        views.ingredient_list, 
        name='ingredient-list'
    ),
    path(
        'ingredients/<int:ingredient_id>/', 
        views.ingredient_detail, 
        name='ingredient-detail'
    ),
    path(
        'contact-us/',
         views.contact,
         name='contact'   
    ),
    path(
        'ingredients/add',
        views.ingredient_create,
        name='ingredient-create'
    ),
    path(
        'ingredients/<int:ingredient_id>/update/',
        views.ingredient_update,
        name='ingredient-update'
    ),
    path(
        'ingredients/<int:ingredient_id>/delete/',
        views.ingredient_delete,
        name='ingredient-delete'
    )

]

foodle/ingredients/models.py
from django.db import models
from ingredients import values as ingredient_values
from django.utils import timezone

# Create your models here.
class Ingredient(models.Model):
    name = models.fields.CharField(max_length=30)
    price = models.fields.DecimalField(
        max_digits=6,
        decimal_places=2
    )
    upload = models.ImageField(
        upload_to ='uploads/',
        blank=True, 
        null=True
    )
    shop = models.fields.IntegerField(
        "Nom du magasin",
        choices=ingredient_values.SHOP_NAME,
        default=0
    ),
    expiration_date = models.fields.DateField(
        "Date de péremption",
        default=timezone.now
    )

    def __str__(self):
        return f'{self.name}'

foodle/ingredients/forms.py
from django import forms
from ingredients.models import Ingredient

class IngredientForm(forms.ModelForm):
    class Meta:
        model = Ingredient
        fields = '__all__'

class ContactUsForm(forms.Form):
    name = forms.CharField(required=False)
    email = forms.EmailField()
    message = forms.CharField(max_length=1000)

foodle/ingredients/views.py
from django.shortcuts import redirect, render
from django.core.mail import send_mail
from .models import Ingredient
from .forms import IngredientForm, ContactUsForm

# Create your views here.
def ingredient_list(request):
    ingredients = Ingredient.objects.all()
    return render(request,
                  'ingredients/ingredient_list.html',
                  {'ingredients': ingredients})

def ingredient_detail(request, ingredient_id):
    ingredient = Ingredient.objects.get(id=ingredient_id)
    return render(request, 
                  'ingredients/ingredient_detail.html',
                  {'ingredient': ingredient})

def ingredient_create(request):
    if request.method == 'POST':
        form = IngredientForm(request.POST)
        if form.is_valid():
            ingredient = form.save()
            return redirect('ingredient-detail', ingredient.id)
    else:
        form = IngredientForm()
    
    return render(request,
                'ingredients/ingredient_create.html',
                {'form': form})

def ingredient_update(request, ingredient_id):
    ingredient = Ingredient.objects.get(id=ingredient_id)

    if request.method == 'POST':
        form = IngredientForm(request.POST, instance=ingredient)
        if form.is_valid():
            form.save()
            return redirect('ingredient-detail', ingredient.id)
    else:
        form = IngredientForm(instance=ingredient)
    return render(request, 
                  'ingredients/ingredient_update.html',
                  {'form': form})

def ingredient_delete(request, ingredient_id):
    ingredient  = Ingredient.objects.get(id=ingredient_id)
    if request.method == 'POST':
        ingredient.delete()
        return redirect('ingredient-list')
    return render(request,
                'ingredients/ingredient_delete.html',
                {'ingredient': ingredient})

def contact(request):   
    if request.method == 'POST':
        # On créé une instance de notre formulaire et on le remplis avec les données POST
        form = ContactUsForm(request.POST)

        if form.is_valid():
            send_mail(
                subject=f'Message from {form.cleaned_data["name"] or "anonyme"} via Foodle Contact Us form',
                message=form.cleaned_data['message'],
                from_email=form.cleaned_data['email'],
                recipient_list=['admin@foodle.xyz']
            )
        return redirect('email-sent')
    # si le formulaire n'est pas valide, On laisse l'exécution continuer jusqu'au return
    # ci-dessous et on affiche à nouveau le formulaire (avec des erreurs).
    else:
        form = ContactUsForm()

    return render(request,
                'ingredients/contact.html',
                {'form': form})

foodle/ingredients/templates/ingredients/base.html
<html>
    <head><title>Foodle</title></head>
    <body>

        {% block content %}{% endblock %}

    </body>
</html>

foodle/ingredients/templates/ingredients/contact.html
<p>Nous sommes là pour vous aider.</p>

<form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
</form>
…

foodle/ingredients/templates/ingredients/ingredient_create.html
{% extends 'ingredients/base.html' %}
{% block content %}

<h1>Ajouter un ingrédient</h1>

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
</form>

{% endblock %}

foodle/ingredients/templates/ingredients/ingredient_delete.html
{% extends 'ingredients/base.html' %}

{% block content %}

<h1>Supprimer le groupe</h1>

<p>Etes-vous sûr de vouloir supprimer cet ingrédient : {{ ingredient.name }}</p>

<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Supprimer">
</form>
{% endblock %}

foodle/ingredients/templates/ingredients/ingredient_detail.html
{% extends 'ingredients/base.html' %}

{% block content %}

<nav>
    <a href="{% url 'ingredient-list' %}">Retour à tous les groupes</a>
</nav>

<h2>{{ ingredient.name }}</h2>

<ul>
 <li>Prix: {{ ingredient.price }}</li>
 <li>Magasin: {{ ingredient.get_shop_display }}</li>
</ul>

<a href="{% url 'ingredient-update' ingredient.id %}">Modifier ce groupe</a> -
<a href="{% url 'ingredient-delete' ingredient.id %}">
    Supprimer
</a>

{% endblock %}

foodle/ingredients/templates/ingredients/ingredient_list.html
{% extends 'ingredients/base.html' %}
{% block content %}

<h1>Ingrédients</h1>

<a href="{% url 'ingredient-create' %}">Ajouter un nouvel ingrédient</a>

<ul>
 {% for ingredient in ingredients %}
    <li>
        <a href="{% url 'ingredient-detail' ingredient.id %}">
            {{ ingredient.name }}
        </a> -
        <a href="{% url 'ingredient-update' ingredient.id %}">
            Mise à jour
        </a> - 
        <a href="{% url 'ingredient-delete' ingredient.id %}">
            Supprimer
        </a>
    </li>
 {% endfor %}
</ul>

{% endblock %}

foodle/ingredients/templates/ingredients/ingredient_update.html
{% extends 'ingredients/base.html' %}
{% block content %}

<h1>Mettre à jour un ingrédient</h1>

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
</form>

{% endblock %}